microsoft/openpaimarketplace

webportal_plugin/src/app/top_bar/components/job_list_dialog.jsx, webportal_plugin/src/app/top_bar/components/job_table.jsx
=> Fix detailslist selection bug

webportal/package-lock.json, webportal/package.json
=> Upgrade node-forge to version 0.10.0 for security

examples/item_protocols/couplet_dataset.yaml, examples/item_protocols/covid_dataset.yaml, examples/item_protocols/grammar_dataset.yaml
disable nfs extra config in covid, couplet and grammar dataset yaml
=> Move covid and grammar dataset to azure blob and disable nfs

webportal/src/app/create_item/components/basic_information.jsx
Data => Data Template
Template => Job Template
=> Update item type in create item

webportal/src/app/create_item/components/basic_information.jsx, webportal/src/app/create_item/components/upload_files.jsx
=> Fix create item UI issues #112

webportal/src/app/market_detail/utils/generate_job_protocol.js
=> Fix wrong task role name in generateJobProtocol

examples/item_protocols/old_templates/sklearn-text-vectorizers.yaml
=> Fix sklearn install in text_vectorizer benchmark

.github/workflows/publish.yml
=> Fix image build and push action (pr/release)

rest_server/marketplace_api.yaml, rest_server/src/controllers/item_controller.js, rest_server/src/models/marketplace_item.js
Test case:
http://localhost:3000/items?keyword=DDP
http://localhost:3000/items?keyword=ddp
http://localhost:3000/items?keyword=Pytorch
http://localhost:3000/items?keyword=pytorch
http://localhost:3000/items?keyword=PyTorch
http://localhost:3000/items?keyword=Keras
http://localhost:3000/items?keyword=keras
http://localhost:3000/items?keyword=OpenPAI
http://localhost:3000/items?
http://localhost:3000/items?keyword=null
=> Update search-by-keyword api and swagger

rest_server/src/models/marketplace_item.js, rest_server/src/models/model_init_handler.js, webportal/src/app/market_detail/components/summary.jsx, webportal/src/app/market_detail/utils/generate_job_protocol.js
A hot fix for v1.4.0. Will create a new version v1.4.1.
1. Check environment variable `process.env.AZURE_STORAGE` exists before insert into database.
2. Add a property `useBlob` in marketplaceItem model as a flag, and only contact `pai_copy` related commands if `useBlob` is true.
=> Hot fix for initializing blob data and using template in v1.4.0 

rest_server/src/models/marketplace_item.js, rest_server/src/models/model_init_handler.js, webportal/src/app/market_detail/components/summary.jsx, webportal/src/app/market_detail/utils/generate_job_protocol.js
Same change of v1.4.1:
1. Check environment variable `process.env.AZURE_STORAGE` exists before insert into database.
2. Add a property `useBlob` in marketplaceItem model as a flag, and only contact `pai_copy` related commands if `useBlob` is true.
=> Refine blob storage usage

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-proposal.md
Examples: https://github.com/microsoft/pai/issues/5219
=> Update issue templates

webportal/package-lock.json, webportal/src/app/market_list/components/item_card.jsx
=> Change item card name from Link to Text

examples/examples.js
=> Change official template author to OpenPAI

webportal/src/app/market_detail/components/summary.jsx
=> Remove the arrow icon in delete item button

webportal/src/app/create_item/components/create_data/data_template.jsx
=> Fix job name invalid when click use data template

webportal/src/app/create_item/components/select_type.jsx
=> Remove the "select form your job list" branch in creating job template as it hasn't been finish

rest_server/marketplace_api.yaml, rest_server/src/models/marketplace_item.js, rest_server/src/models/model_init_handler.js
=> Change marketplace item schema

webportal/src/app/market_detail/components/pivot_card.jsx
=> Add a new column of `protocol` in item detail page

webportal/src/app/market_detail/components/summary.jsx, webportal/src/app/utils/marketplace_api.js
=> Add 'Delete' disable and fix my template typo

.github/ISSUE_TEMPLATE/feature-proposal.md
Remove demo section and add process check list section
=> Update feature proposal issue template

rest_server/package-lock.json, rest_server/package.json, rest_server/src/controllers/item_controller.js, rest_server/src/utils/protocol.js
=> [MP restserver] Validate post /items  protocol format align with pai

rest_server/src/controllers/item_controller.js
=> Fix read permission check for item get

webportal/src/app/market_list/market_list.jsx
=> fix create template button in my template page

webportal/src/app/market_detail/components/copy_popup.jsx, webportal/src/app/market_detail/components/share_options.jsx, webportal/src/app/market_detail/components/summary.jsx
=> Copy template with popup window and share options

webportal/src/app/market_detail/components/copy_popup.jsx, webportal/src/app/market_detail/components/edit_popup.jsx, webportal/src/app/market_detail/components/share_options.jsx, webportal/src/app/market_detail/components/summary.jsx, webportal/src/app/market_detail/market_detail.jsx, webportal/src/app/utils/marketplace_api.js
=> Add edit template and fix copy item bugs

webportal/src/app/create_item/components/create_job/basic_information.jsx
Short summary and description will not be required for creating job item.
=> Remove required from short summary and description in create job items

webportal/package-lock.json, webportal/package.json, webportal/src/app/market_detail/components/access_info.jsx, webportal/src/app/market_detail/components/pivot_card.jsx, webportal/src/app/market_detail/components/summary.jsx, webportal/src/app/market_detail/market_detail.jsx
#284 
Edit icons:
After click name edit icon button
After click edit description, and the save button will show
=> Market item edit in place (name, summary, description)

rest_server/src/controllers/category_controller.js, rest_server/src/models/error.js, rest_server/src/models/index.js, rest_server/src/models/item_category.js, rest_server/src/models/item_tag.js, rest_server/src/router.js
Tag and Category API design #296
=> Add tags and categories API

rest_server/src/models/marketplace_item.js
=> fix the keyword search error in list items

rest_server/src/controllers/item_controller.js, rest_server/src/models/marketplace_item.js
Use keyword search may cause the 500 error
So I add table name here.
The details:
=> Fix database error: column reference is ambiguous

webportal/src/app/market_detail/components/pivot_card.jsx
Fix #315
Add button here:
Old:
=> Add cancel button for edit item description
